### ISSUE TITLE
Pixelage Build error

### ISSUE THREAD

**Issue by BushidoOT** [ProjectPixelage/android_manifest#2]
[ 31% 30596/98104] //frameworks/base/packages/CredentialManager:CredentialManager r8 [common]
Warning: An API level of 35 is not supported by this compiler. Please use an API level of 34 or earlier
[ 31% 30620/98104] //frameworks/base/packages/EasterEgg:EasterEgg r8 [common]
Warning: An API level of 35 is not supported by this compiler. Please use an API level of 34 or earlier
20:28:28 ninja failed with: exit status 137
how fix ?
![image](https://github.com/user-attachments/assets/809f6207-c78f-404f-95ed-0423a1063b5c)

**Comment by clarencelol** [comment]
Please learn how to read why it fails

The API thingy is just a warning also its AOSP 

The real reason it failed because of your RAM is not enough
