### ISSUE TITLE
RuntimeError: sum of sizes of ['odm', 'product', 'system', 'system_ext', 'vendor'] is greater than BOARD_SUPER_PARTITION_SIZE / 2:

### ISSUE THREAD

**Issue by Orthoxodus** [ProjectPixelage/android_manifest#3]
![photo_2024-12-29_08-57-32](https://github.com/user-attachments/assets/1cfc608b-10b8-4737-a484-f8363b3780bf)

**Comment by QuinceROMs** [comment]
Fix your tree. It's not the sources' fault.

**Comment by Orthoxodus** [comment]
Yeah, yeah then how I'm able to build any rom only this can't build..
